# Site settings
title: Visually Computational
email: milan.lajtos@me.com
description: >
  Take it with a grain of salt.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mlajtos.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mlajtos

# Build settings
markdown: kramdown
